In [1]:
# Load libraries
import pandas as pd
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.svm import SVC
from scipy import stats
import seaborn as sns
import numpy as np

In [2]:
data = pd.read_csv("hawker_centre_modified_short.csv")
#Adding the dataset and turning it into a dataframe
data.head()

,name_of_centre,postal_code,location_of_centre,type_of_centre,owner,no_of_stalls,no_of_cooked_food_stalls,no_of_mkt_produce_stalls,Latitude,Longitude
0,Adam Road Food Centre,289876,"2, Adam Road",HC,Government,32,32,0,1.32926,103.81452
1,Amoy Street Food Centre,69111,"National Development Building, Annex B, Telok ...",HC,Government,135,134,1,1.28944,103.84998
2,Bedok Food Centre,469572,"1, Bedok Road",HC,Government,32,32,0,1.32659,103.95121
3,Beo Crescent Market,169982,"38A, Beo Crescent",MHC,Government,94,32,62,1.28864,103.82764
4,Berseh Food Centre,208877,"166, Jalan Besar",HC,Government,66,66,0,1.30578,103.85554

In [3]:
data.describe()

,postal_code,no_of_stalls,no_of_cooked_food_stalls,no_of_mkt_produce_stalls,Latitude,Longitude
count,33.000000,33.000000,33.000000,33.00000,33.000000,33.000000
mean,288985.272727,116.545455,58.545455,58.00000,1.310383,103.842926
std,174100.126842,84.297127,31.542720,72.50862,0.026512,0.046327
min,48940.000000,21.000000,16.000000,0.00000,1.280730,103.721626
25%,151115.000000,63.000000,32.000000,0.00000,1.289440,103.817009
50%,208877.000000,94.000000,51.000000,48.00000,1.305780,103.839730
75%,424768.000000,161.000000,83.000000,82.00000,1.320440,103.865840
max,618499.000000,365.000000,134.000000,302.00000,1.380500,103.951210

In [4]:
import requests # library to handle requests
import random # library for random number generation

!conda install -c conda-forge geopy --yes 
from geopy.geocoders import Nominatim # module to convert an address into latitude and longitude values

# libraries for displaying images
from IPython.display import Image 
from IPython.core.display import HTML 
    
# tranforming json file into a pandas dataframe library
from pandas.io.json import json_normalize

!conda install -c conda-forge folium=0.5.0 --yes
import folium # plotting library

print('Folium installed')
print('Libraries imported.')

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.

Folium installed
Libraries imported.

In [5]:
CLIENT_ID = 'TD5QDZZRT1HRKRDRY3ELQIJI4DNBT3X3IAKLLETWN4B1OYBN' # your Foursquare ID
CLIENT_SECRET = 'Q3H2QHFFJ5NYLYN5R1S2TG0NS4JR2IHY3BCCWFORPV534JR5' # your Foursquare Secret
VERSION = '20200420'
LIMIT = 30
print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: TD5QDZZRT1HRKRDRY3ELQIJI4DNBT3X3IAKLLETWN4B1OYBN
CLIENT_SECRET:Q3H2QHFFJ5NYLYN5R1S2TG0NS4JR2IHY3BCCWFORPV534JR5

In [10]:
def getNearbyVenues(names, latitudes, longitudes):
    radius=500
    LIMIT=100
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, ) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = [ 
                  'CenterName', 
                  'Latitude', 
                  'Longitude','no_of_stalls','no_of_cooked_food_stalls']
    
    return(nearby_venues)

In [11]:
df = getNearbyVenues(names=data['name_of_centre'],
                                   latitudes=data['Latitude'],
                                   longitudes=data['Longitude'],
                     
                                  )

Adam Road Food Centre
Amoy Street Food Centre
Bedok Food Centre
Beo Crescent Market
Berseh Food Centre
Bukit Timah Market
Chomp Chomp Food Centre
Commonwealth Crescent Market
Dunman Food Centre
East Coast Lagoon Food Village
Geylang Serai Market
Golden Mile Food Centre
Holland Village Market & Food Centre
Kallang Estate Market
Market Street Food Centre
Newton Food Centre
North Bridge Road Market & Food Centre
Pasir Panjang Food Centre
Serangoon Garden Market
Sembawang Hill Food Centre
Taman Jurong Market & Food Centre
Tanglin Halt Market
Tiong Bahru Market
Zion Riverside Food Centre
ABC Brickworks Market & Food Centre
Albert Centre Market & Food Centre
Alexandra Village Food Centre
Blk 1 Jalan Kukoh
Blk 105 Hougang Ave 1
Blk 11 Telok Blangah Crescent
Blk 112 Jalan Bukit Merah
Blk 115 Bukit Merah View
Blk 117 Aljunied Ave 2

ValueError: Length mismatch: Expected axis has 3 elements, new values have 5 elements

In [8]:
df.head()

                   Venue  Venue Latitude  Venue Longitude
0  Adam Road Food Centre         1.32926        103.81452
1  Adam Road Food Centre         1.32926        103.81452
2  Adam Road Food Centre         1.32926        103.81452
3  Adam Road Food Centre         1.32926        103.81452
4  Adam Road Food Centre         1.32926        103.81452